### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by vanvd** [bajicdusko/JavaCVWowzaStarterKit#2]
Hi bajicdusko,
thank for your project, but i have a error when build it:
LiveBroadcastActivityPermissionsDispatcher.initCameraWithCheck(this);

please let me know what is LiveBroadcastActivityPermissionsDispatcher.
how i can fix it?
Thank you!

**Comment by bajicdusko** [comment]
PermissionDispatcher i autogenerated class. You just need to rebuild your
project.

**Comment by vanvd** [comment]
thank you!
