### ISSUE TITLE
onPreviewFrame not called

### ISSUE THREAD

**Issue by okpatil4u** [bajicdusko/JavaCVWowzaStarterKit#3]
Hi there,

I am running your code as is without any changes.
But onPreviewFrame callback is not belling called. It's just audio stream being encoded into the rtmp stream.

Can you help ?
Cheers

**Comment by bajicdusko** [comment]
Hello @okpatil4u, i did'nt had much spare time lately. I will update javacv library and try it myself. I'll let you know then (tomorrow). Cheers.

**Comment by okpatil4u** [comment]
Thanks @bajicdusko. Any progress on this ?

**Comment by bajicdusko** [comment]
@okpatil4u I've pushed some fixes, new JavaCPP version and few refactors. It works on my side, though. What device you are using and which android version is it running on?

**Comment by okpatil4u** [comment]
@bajicdusko, thanks dude. It works. I am closing this issue.

**Comment by bajicdusko** [comment]
Glad I could help @okpatil4u . If you implement even advanced options, feel free to pull request :)

**Comment by okpatil4u** [comment]
SUre @bajicdusko. And thanks again for your help !
