### ISSUE TITLE
RTMP error

### ISSUE THREAD

**Issue by refreshlearn** [bajicdusko/JavaCVWowzaStarterKit#4]
Hi,

I am trying to create an android application for live streaming through mobile camera.
I am using Wowza server, but I am getting an errors

1. "FrameRecorder$Exception: avio_open error() error : Could not open url ...."
I am using RTMP protocol, tried with flv & m3u8 formats. I basically need in m3u8 format.

2. At time I get below error also
No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)

3. Sometimes
E/linker: library "/system/lib/libdl.so" ("/system/lib/libdl.so") needed or dlopened by...

Thanks in advance. It would be of great help in solving these issues.

Regards,
refreshlearn

**Comment by bajicdusko** [comment]
@refreshlearn Hi, are you targeting the proper url. Setting the stream name, application name, port correctly? As for the formats, once you're able to connect to media engine, it should either fail to stream or you'd see a black screen. 

Generally, this lib needs a refactoring, for which I don't have enough time at the moment. Any pull request is welcome.

**Comment by refreshlearn** [comment]
Thank you for your valuable reply. Yes the issue was with some
configuration related to Wowza Server though the parameters like stream
name, application name were correctly mentioned. The Application is working
very well. :)

**Comment by bajicdusko** [comment]
I'm glad you were able to solve the issue. Feel free to star the repository as the rewrite is eminent :). Cheers.
